# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

class Student:
    def __init__(self, name, age, marks):
        self.name = name
        self.age = age
        self.marks = marks

# Creating an object
s1 = Student("Kakul", 18, 85)

# Displaying values
print("Name:", s1.name)
print("Age:", s1.age)
print("Marks:", s1.marks)